before_install:
 - cd DHARMa
 
language: r

# Enable if a more recent version of Ubuntu is helpful.
# This gives us g++-4.8, which is needed for C++11 (e.g. ranger package)
# dist: trusty

# Disable sudo so that we can use container infrastructure and package caching.
sudo: false
# Enable sudo so that we can use apt-get to upgrade and install linux packages.
# We also need sudo for r_binary_packages listed below.
# sudo: required

# This only works if sudo = false.
cache: packages

r_github_packages:
  - glmmTMB/glmmTMB/glmmTMB

r:
  - oldrel
  - release
  - devel
  
# Install nlopt package to help nloptr install.
addons:
  apt:
    packages:
      - libnlopt-dev
